version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin  # Change this
      POSTGRES_PASSWORD: admin  # Change this
      POSTGRES_DB: metadata_db
    ports:
      - "5432:5432"  # PostgreSQL runs on port 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metadata_db
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: admin
      MB_DB_HOST: postgres
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/data

configs:
  qdrant_config:
    content: |
      log_level: INFO


volumes:
  postgres-data:

