[tool.poetry]
name = "summerschool-rag-project"
version = "0.1.0"
description = ""
authors = ["Gabriel9753 <gabriel.elias2000@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.2"
seaborn = "^0.13.2"
numpy = "^2.1.1"
tqdm = "^4.66.5"
ipykernel = "^6.29.5"
pyarrow = "^17.0.0"
plotly = "^5.24.0"
nbformat = "^5.10.4"
streamlit-agraph = "^0.0.45"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
